### ISSUE TITLE
Slow in windows

### ISSUE THREAD

**Issue by sverrejb** [realfagskjelleren/rfid#7]
The system seems to run slow under windows. Win 7, medium-high specced PC.

**Comment by melwil** [comment]
Define "run slow", do commands lag? Does it take a long time to display information?

**Comment by sverrejb** [comment]
Commands lag. Up to 10-15 sec delay from inputing rfid to any response is given.

**Comment by melwil** [comment]
Sounds like nothing I've experienced. It's very snappy in every operating system for me. Are you sure your internet connection is good?

**Comment by sverrejb** [comment]
Worked fine on my laptop (ubuntu 12.04) on the same network. Will investigate later.

**Comment by melwil** [comment]
Alright. There's really not any particularly heavy operations at any point in the system, and all SQL is performed server-side, so I don't see why one OS would be slower than another in any case.

The RFID application itself is a simple I/O program that should be near instantaneous for any computer.

**Comment by sverrejb** [comment]
Confirmed, slow due to crappy internet @ valøyvegen.
