### ISSUE TITLE
Sum of purchases made per card seem to not be correct

### ISSUE THREAD

**Issue by johnhans** [realfagskjelleren/rfid#8]
Had a customer on Saturday that had a card where the sum did not increase after buying more things, but actually decreased... COuld be worth checking out?

**Comment by melwil** [comment]
Did you write down The rfid og The card, by any chance?

**Comment by johnhans** [comment]
On 10.02.14 10:53, Håvard Slettvold wrote:

> Did you write down The rfid og The card, by any chance?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/realfagskjelleren/rfid/issues/8#issuecomment-34614569

Nope, but I assume that if this happens on one card, then it should on 
others... It could be tested by just running several transactions, 
depositing money and buying merchandise, and then checking that the 
amount actually increases by a sensible amount.

## 

John Hanssen Kolstad

**Comment by melwil** [comment]
I'm pretty sure this hasn't continued to happen, so I'm going to close it for now.
